In [1]:
"hello world"

'hello world'

In [2]:
v=90
v1="abc"
v2=90.67
v3= True
v4=6+9j

In [3]:
v1

'abc'

In [4]:
v2

90.67

#data structures
-list
-tuple
-dictionary
-set

In [ ]:
l1=[1,2,3,4,5,"abc"]
l1[3]=6
l1

In [ ]:
l1.append(0)
l1
l1.insert(1,7)
l1

In [ ]:
-append(add data in end )
-extend(add data from  another data)
-insert(insert data in given indexing)
-remove(remove value)
-pop(by defualt delete last element)
-del(to delete entire list)
-clear(clear data)

In [ ]:
t1=("a","b","c")
t1[1]

In [ ]:
type(t1)

In [ ]:
max(t1)

In [ ]:
min(t1)

In [ ]:
t2=(1,2,3)
t1+t2

In [ ]:
#dictionary

In [ ]:
dict1={"a":"monday","b":"tuesday"}
dict1

In [ ]:
dict1["b"]="wednesday"

In [ ]:
dict1

In [ ]:
#set

In [ ]:
s1={1,2,3,3,2,4}
s1

In [ ]:
s1.add(12)
s1

In [ ]:
s1.add(10)

In [ ]:
s1

In [ ]:
s1.remove(10)
s1

In [ ]:
#methods of set
-issuperset()
-issubset()
-union() |
-intersection()&
-difference() -
-symmetric_difference() ^

In [ ]:
#control statements
##conditional statement 
if
elif
if else
nested if
##loops
while
for
##jump statement
break
continue
pass

In [ ]:
age=int(input("Enter age:"))
if(age>=18):
    print("you are eligible for voting")
else:
    print("you are not eligible for voting")
    

In [ ]:
#find the largest number out of 3 no 
take user input

In [ ]:
i1=int(input("no1"))
i2=int(input("no2"))
i3=int(input("no3"))
if(i1>i2):
    if(i1>i3):
        print(i1)
    else:
        print(i3)
if(i1<i2):
    if(i2>i3):
        print(i2)
    else:
        print(i3)

In [ ]:
whether the entered no is a prime or not 

In [ ]:
no = int(input("Enter a number: "))
if (no <= 1):
    print("Not a prime number")
else:
    for i in range(2, no):
        if (no % i == 0):
            print("Not a prime number")
            break
    else:
        print("Prime number")

In [ ]:
for i in range(1,100,2):
    print(i, end =',')

In [ ]:
st='Anoop'
for i in st:
    print(i)

In [ ]:
dict2={"roll_no":"1","name":"Neha","email":"neha@gmail.com"}
#keys(for keys),values(for values),items(for both)
for n,m in dict2.items():
    print(n,"=",m)

In [3]:
print('''
       enter 1 to print table
       enter 0 to exit
    ''')

while True:
    ch=input("enter your choice:")
    if (ch=="1"):
        num=int(input("enter no:"))
        for a in range(1,11):
            print(num,"x",a,"=",num*a)
    elif (ch=="0"):
        break
    else:
        print("invalid choice")
    
            


       enter 1 to print table
       enter 0 to exit
    


enter your choice: 1
enter no: 2


2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20


enter your choice: 3


invalid choice


enter your choice: 1
enter no: 3


3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30


enter your choice: 0


In [12]:
#continue and pass
for i in range(10):
    if(i==5):
        continue
    print(i)

0
1
2
3
4
6
7
8
9


In [36]:
num1=int(input("enter number 1"))
num2=int(input("enter number 2"))
op=input("enter operation")
if(op=="*"):
    print(num1*num2)
elif(op=="+"):
    print(num1+num2)
elif(op=="-"):
    print(num1-num2)
else:
    print("invalid operation")

enter number 1 2
enter number 2 3
enter operation 4


invalid operation


In [27]:
#NON-PARA
def fun1():
    print("abc")
fun1()

abc


In [37]:
#parameterized function
#positional
def add(a,b):
    return a+b
add(2,9)

11

#types of arguments
-positional
-default
-keyword
-abb(var length)

In [41]:
#default
def add(a=2,b=3):
    return a+b
add()

5

In [47]:
#keyword
def add(a,b):
    return a+b
add(9,b=3)

12

In [55]:
#arbitary abb(var length)
def add(*a):
    return a
add(2,9,9,0)

(2, 9, 9, 0)

In [1]:
#abb(var length) argument keyword 
def add(v,**a):    #return in dictionary
    return v,a
add(45,a=2,b=2)

(45, {'a': 2, 'b': 2})

In [20]:
 class parent:
     ##data member/attribute
     a=90
     b="string"
     ##member function /method
     def working(s):  #mandatory parameter self/s/f/b
         print("i am a class's method")
obj=parent()


In [21]:
obj

In [22]:
obj.working()

i am a class's method


In [ ]:
###oops
-classes
-objects
-inheritance
-polymorphism
-encapsulation
-abstraction

In [ ]:
###numpy
nummeric python

In [ ]:
-vector[1d array]
-matrix[>1d array]

In [ ]:
###1-d array

In [24]:
!pip install numpy

In [25]:
import numpy as np

In [ ]:
###methods to create an arrays
-array() -list,tuple
-arange() -create an array within a particular range
-linspace() -provide no. of values within the range
-ones() -provide ones array
-zeroes()-provide zeroes array
-eye() -provide identity matrix
-random -rand,randint,uniform

In [43]:
list1=['abc','ccb','ccc','cdc','cce','cfc']
arr=np.array(list1)
print(arr)

['abc' 'ccb' 'ccc' 'cdc' 'cce' 'cfc']


In [44]:
type(arr)

numpy.ndarray

In [45]:
arr.dtype

dtype('<U3')

In [72]:
list2=[[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]],[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]]
arr=np.array(list2)
print(arr)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]


 [[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]]


arr2

In [73]:
arr[1][1]=90

In [74]:
arr

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[90, 90, 90],
         [90, 90, 90],
         [90, 90, 90]]]])

In [75]:
arr.ndim

4

In [76]:
arr.shape

(2, 2, 3, 3)

In [60]:
###ones array
arr3=np.ones((3,4),dtype='int')
print(arr3) 

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [61]:
arr3=np.zeros((3,4),dtype='int')
print(arr3)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [62]:
arr3=np.ones((3,4),dtype='int')*5
print(arr3) 

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
##create an array--identity,arange,linspace

In [95]:
arr4=np.eye((5),dtype='int')*5555
print(arr4)

[[5555    0    0    0    0]
 [   0 5555    0    0    0]
 [   0    0 5555    0    0]
 [   0    0    0 5555    0]
 [   0    0    0    0 5555]]


In [102]:
arr5=np.arange(1,5,dtype='int')
print(arr5)

[1 2 3 4]


In [104]:
arr5.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [110]:
arr6=np.linspace(1,50,100)
print(arr6)

[ 1.          1.49494949  1.98989899  2.48484848  2.97979798  3.47474747
  3.96969697  4.46464646  4.95959596  5.45454545  5.94949495  6.44444444
  6.93939394  7.43434343  7.92929293  8.42424242  8.91919192  9.41414141
  9.90909091 10.4040404  10.8989899  11.39393939 11.88888889 12.38383838
 12.87878788 13.37373737 13.86868687 14.36363636 14.85858586 15.35353535
 15.84848485 16.34343434 16.83838384 17.33333333 17.82828283 18.32323232
 18.81818182 19.31313131 19.80808081 20.3030303  20.7979798  21.29292929
 21.78787879 22.28282828 22.77777778 23.27272727 23.76767677 24.26262626
 24.75757576 25.25252525 25.74747475 26.24242424 26.73737374 27.23232323
 27.72727273 28.22222222 28.71717172 29.21212121 29.70707071 30.2020202
 30.6969697  31.19191919 31.68686869 32.18181818 32.67676768 33.17171717
 33.66666667 34.16161616 34.65656566 35.15151515 35.64646465 36.14141414
 36.63636364 37.13131313 37.62626263 38.12121212 38.61616162 39.11111111
 39.60606061 40.1010101  40.5959596  41.09090909 41.

In [111]:
arr6.size

100

In [ ]:
#random module
-randint (provide a array of random integer in a specific range)
-rand  (array of random number in between 0-1)
-uniform (array of random decimal no. in a specific range)

In [2]:
import numpy as np

In [15]:
arr7=np.random.rand(3,4,5) #dimension,row,coloumn
arr7

array([[[0.38652075, 0.81185274, 0.74925592, 0.26912436, 0.92835915],
        [0.20791195, 0.17585855, 0.68907421, 0.22350641, 0.51631432],
        [0.81366233, 0.00099344, 0.49987235, 0.12274643, 0.31078342],
        [0.50056777, 0.4850314 , 0.05814769, 0.38283808, 0.79329711]],

       [[0.46204249, 0.29994692, 0.53495383, 0.0215732 , 0.97676744],
        [0.13143298, 0.51217006, 0.12690386, 0.77401976, 0.35435584],
        [0.30814517, 0.28849338, 0.85079267, 0.4681978 , 0.210264  ],
        [0.69967936, 0.02529054, 0.52737361, 0.38136483, 0.01954509]],

       [[0.9081372 , 0.47709527, 0.64826496, 0.19228448, 0.295056  ],
        [0.62937119, 0.58028764, 0.48419981, 0.10591579, 0.43465992],
        [0.7574545 , 0.47093489, 0.57918352, 0.67071558, 0.50800867],
        [0.01883207, 0.35953274, 0.24703677, 0.98646457, 0.0785738 ]]])

In [26]:
arr8=np.random.randint(3,9,size=(3,3))
arr8

array([[4, 3, 5],
       [8, 6, 5],
       [6, 5, 5]])

In [27]:
import numpy.random as rd
#or from numpy import random as rd

In [32]:
arr9=rd.uniform(0,10,size=(4,4))
arr9

array([[7.00191389, 9.47149862, 7.70739616, 6.82091985],
       [4.29838191, 2.85805896, 1.41205369, 1.2128641 ],
       [0.29941564, 0.64152019, 7.21148122, 2.57142375],
       [8.86499138, 4.27856891, 0.12568984, 6.95115873]])

In [ ]:
#array operation
-sum()
-min()
-max()
-sqrt()
-mean()
-std()
-argmax()

In [33]:
arr10=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr10)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
np.sum(arr10)

45

In [35]:
arr10.sum()

45

In [40]:
arr10.sum(1) #0 for along  coloumn and 1 for along row 

array([ 6, 15, 24])

In [41]:
arr10.min()

1

In [44]:
arr10.min(1) #0 for along  coloumn and 1 for along row 

array([1, 4, 7])

In [45]:
arr10.std()

2.581988897471611

In [ ]:
#check mean ,mean along rows and coloumns, sqrt

In [47]:
arr10.mean()

5.0

In [49]:
arr10.mean(1)

array([2., 5., 8.])

In [50]:
arr10.mean(0)

array([4., 5., 6.])

In [52]:
np.sqrt(arr10)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [55]:
arr10.argmin()

0

In [56]:
arr10.argmax()

8

In [57]:
###Pandas
-series (1d data)
-dataframe (2d data)

In [58]:
!pip install pandas

In [68]:
import pandas as pd

In [72]:
list11=[1,2,3,4,5,6,7]
sr=pd.Series(list11) 
print(sr)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64


In [73]:
df=sr.to_frame()
print(df)

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7


In [ ]:
###methods to create dataframe
-list of lists
-list of tuple
-tuple of tuples
-tuple pf lists
-list of dictionary
-dictionary of lists
-read_excel()
-read_csv()
-read_json()
-json_normalize
-read_html()

In [81]:
dict23={
      "Temp":[12,34,56,21,0],
      "Hum":[45,33,12,22,12],
      "Events":["Rainy","Sunny","Sunny","Cloudy","Snow"]
}

In [89]:
weather=pd.DataFrame(dict23) 
print(weather)

   Temp  Hum  Events
0    12   45   Rainy
1    34   33   Sunny
2    56   12   Sunny
3    21   22  Cloudy
4     0   12    Snow


In [87]:
list23=[
    [12,45,"Rainy"],
    [34,33,"Sunny"]
]

In [95]:
df1=pd.DataFrame(list23,columns=["Temp","Hum","Event"])
print(df1)

   Temp  Hum  Event
0    12   45  Rainy
1    34   33  Sunny


In [96]:
!pip install html5lib

In [109]:
html=pd.read_html("https://en.wikipedia.org/wiki/Economy_of_India")
df4=html[3]

In [110]:
df4.to_csv("economy.csv")

In [119]:
csv=pd.read_csv(r"C:\Users\Anoop Arpan\Downloads\Salary_Data.csv")
csv

YearsExperience   Age  Salary
0               1.1  21.0   39343
1               1.3  21.5   46205
2               1.5  21.7   37731
3               2.0  22.0   43525
4               2.2  22.2   39891
5               2.9  23.0   56642
6               3.0  23.0   60150
7               3.2  23.3   54445
8               3.2  23.3   64445
9               3.7  23.6   57189
10              3.9  23.9   63218
11              4.0  24.0   55794
12              4.0  24.0   56957
13              4.1  24.0   57081
14              4.5  25.0   61111
15              4.9  25.0   67938
16              5.1  26.0   66029
17              5.3  27.0   83088
18              5.9  28.0   81363
19              6.0  29.0   93940
20              6.8  30.0   91738
21              7.1  30.0   98273
22              7.9  31.0  101302
23              8.2  32.0  113812
24              8.7  33.0  109431
25              9.0  34.0  105582
26              9.5  35.0  116969
27              9.6  36.0  112635
28             10.3  37.0  122391
29             10.5  38.0  121872

In [124]:
csv.head(10)

YearsExperience   Age  Salary
0              1.1  21.0   39343
1              1.3  21.5   46205
2              1.5  21.7   37731
3              2.0  22.0   43525
4              2.2  22.2   39891
5              2.9  23.0   56642
6              3.0  23.0   60150
7              3.2  23.3   54445
8              3.2  23.3   64445
9              3.7  23.6   57189

In [125]:
csv.tail(10)

YearsExperience   Age  Salary
20              6.8  30.0   91738
21              7.1  30.0   98273
22              7.9  31.0  101302
23              8.2  32.0  113812
24              8.7  33.0  109431
25              9.0  34.0  105582
26              9.5  35.0  116969
27              9.6  36.0  112635
28             10.3  37.0  122391
29             10.5  38.0  121872

In [127]:
weather.to_json("wth.json")

In [129]:
jdata=pd.read_json("wth.json")

In [130]:
jdata

Temp  Hum  Events
0    12   45   Rainy
1    34   33   Sunny
2    56   12   Sunny
3    21   22  Cloudy
4     0   12    Snow

In [132]:
type(jdata)

pandas.core.frame.DataFrame

In [137]:
 jdata[["Temp","Events"]]

Temp  Events
0    12   Rainy
1    34   Sunny
2    56   Sunny
3    21  Cloudy
4     0    Snow

In [142]:
jdata.loc[1:2,["Temp","Events"]]

Temp Events
1    34  Sunny
2    56  Sunny

In [146]:
jdata.loc[4]

Temp         0
Hum         12
Events    Snow
Name: 4, dtype: object

In [153]:
jdata.iloc[0:3,0:2]

Temp  Hum
0    12   45
1    34   33
2    56   12

In [158]:
jdata[jdata["Temp"]>45]

Temp  Hum Events
2    56   12  Sunny

In [159]:
jdata.describe()

Temp        Hum
count   5.000000   5.000000
mean   24.600000  24.800000
std    21.512787  14.237275
min     0.000000  12.000000
25%    12.000000  12.000000
50%    21.000000  22.000000
75%    34.000000  33.000000
max    56.000000  45.000000

In [160]:
list23=[
    [12,45,"Rainy",np.nan],
    [34,33,"Sunny",23]
]

In [162]:
df7=pd.DataFrame(list23)
df7

0   1      2     3
0  12  45  Rainy   NaN
1  34  33  Sunny  23.0

In [184]:
df7.isnull().sum()

0    0
1    0
2    0
3    1
dtype: int64

In [188]:
df7.fillna(df7[3].median())

0   1      2     3
0  12  45  Rainy  23.0
1  34  33  Sunny  23.0

In [189]:
df7.fillna(0)

0   1      2     3
0  12  45  Rainy   0.0
1  34  33  Sunny  23.0

In [192]:
df7[4]=[12,67] #to add new column

In [193]:
df7

0   1      2     3   4
0  12  45  Rainy   NaN  12
1  34  33  Sunny  23.0  67